[package]
name = "paper_cache"
version = "1.5.13"
edition = "2021"

[dependencies]
dlv-list = "0.6.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.13.2" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.1" }
thiserror = "2.0.7"
dashmap = "6.1.0"
crossbeam-channel = "0.5.13"
typesize = "0.1.10"
byteorder = "1.5.0"
tempfile = "3.14.0"
parking_lot = "0.12.3"
log = "0.4.22"
