[package]
name = "paper_cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1.0"
dlv-list = "0.5.1"
kwik = { git = "https://github.com/KiaShakiba/kwik-rs.git", version = "0.1.0" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", version = "0.1.0" }
thiserror = "1.0.56"
