[package]
name = "paper_cache"
version = "1.5.14"
edition = "2021"

[dependencies]
dlv-list = "0.6.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.14.7" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.1" }
thiserror = "2.0.11"
dashmap = "6.1.0"
crossbeam-channel = "0.5.14"
typesize = "0.1.11"
byteorder = "1.5.0"
tempfile = "3.16.0"
parking_lot = "0.12.3"
log = "0.4.25"
