[package]
name = "paper_cache"
version = "1.3.4"
edition = "2021"

[dependencies]
rustc-hash = "2.0.0"
dlv-list = "0.5.2"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.7.0" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.1.0" }
thiserror = "1.0.61"
dashmap = "6.0.1"
crossbeam-channel = "0.5.13"
