[package]
name = "paper_cache"
version = "1.5.10"
edition = "2021"

[dependencies]
dlv-list = "0.5.2"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.11.6" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.1" }
thiserror = "1.0.64"
dashmap = "6.1.0"
crossbeam-channel = "0.5.13"
typesize = "0.1.9"
byteorder = "1.5.0"
tempfile = "3.13.0"
parking_lot = "0.12.3"
