[package]
name = "paper_cache"
version = "1.8.2"
edition = "2021"

[dependencies]
dlv-list = "0.6.0"
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.15.6" }
paper_utils = { git = "ssh://git@github.com/Paper-Book/paper-utils.git", tag = "v1.2.2" }
thiserror = "2.0.12"
dashmap = "6.1.0"
crossbeam-channel = "0.5.14"
typesize = "0.1.13"
byteorder = "1.5.0"
tempfile = "3.19.1"
parking_lot = "0.12.3"
log = "0.4.27"
nohash-hasher = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
